[phases.setup]
nixPkgs = ["python312", "postgresql"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt && pip install gunicorn"]

[start]
cmd = "cd backend && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn sbcc.wsgi:application --bind 0.0.0.0:$PORT"
